# Site settings
title: Knowledge in the image of inquiry
author: Erik Hoversten

description: >
  It is commonly suggested that knowledge is the end of inquiry. But what implications are there for the nature of knowledge if we take this idea seriously?
baseurl: "/kitioi"
url: "http://erikhoversten.org"

email: ehovers10@gmail.com
github_username:  ehovers10
copy: true

# Build settings
markdown: kramdown
