# Site settings
title: Discourse as collaborative inquiry
author: Erik Hoversten
description:
  I contend that conversation commonly realizes a collaborative inquiry, which is to say that successful contribution to the discourse requires the efforts of multiple parties working in concert, not just serially. It is the goal of this project to explain, motivate, and provide a model of implementation for this idea, what I call <em>collaborative discourse dynamics</em>.

baseurl: ""
url: "http://erikhoversten.org"

email: ehovers10@gmail.com
github_username:  ehovers10
copy: true
bibliography: ''

# Build settings
markdown: kramdown

kramdown:
  hard_wrap: false

examples: examples

formalism:
  data: "formalism"
  wraps: "wraps"

bibliography:
  source: dissbib
  style:
    reference: Eref1
    citation: CiteEH

notes:
  folder: notes

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
  - scope:
      path: ""
      type: "appendices"
    values:
      layout: "article"

collections:
  chapters:
    output: true
    render: true
  appendices:
    output: true
  snippets:
    output: false

exclude: [deprecated,sections,mustache]
